version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: trackfolio-postgres
    environment:
      POSTGRES_DB: trackfolio
      POSTGRES_USER: trackfolio
      POSTGRES_PASSWORD: trackfolio
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    container_name: trackfolio-adminer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"

volumes:
  dbdata:
