spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trackfolio
    username: trackfolio
    password: trackfolio
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # don’t auto-create schema; Flyway will handle migrations
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080
